[theme]
primaryColor = "#00C853"   # Color principal
backgroundColor = "#121212"  # Color de fondo del body
secondaryBackgroundColor = "#1F1F1F"  # Color del fondo del sidebar
textColor = "#FFFFFF"  # Color del texto
