[theme]
primaryColor = "#277fa5"   # Color principal
backgroundColor = "#2a2a2a"  # Color de fondo del body
secondaryBackgroundColor = "#000000"  # Color del fondo del sidebar
textColor = "#FFFFFF"  # Color del texto
